import streamlit as st
from panini.modules.separate_characters import separate_characters_and_map
from panini.modules.halant_handling import group_sanskrit_characters
from panini.modules.merging_in_list import merge_characters
from panini.modules.guna1_1_2 import get_guna_vowels, identify_guna_vowels, explain_guna
from panini.modules.separate_characters import separate_characters_and_map
from panini.modules.halant_handling import group_sanskrit_characters
from panini.modules.merging_in_list import merge_characters
